version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      mui:
        patterns:
          - "@mui/*"
          - "@fontsource/*"
      emotion:
        patterns:
          - "@emotion/*"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
      eslint-and-typescript:
        patterns:
          - "eslint"
          - "eslint-*"
          - "eslint-plugin-*"
          - "@typescript-eslint/*"
          - "typescript"
